export interface TILE_VARIANTSI {
  GROUND_LAYER: {
    GRASS: { TILE_MAP_INDEX: number }
    DIRT: { TILE_MAP_INDEX: number }
    MOUNTAIN: { TILE_MAP_INDEX: number }
    WATER: {
      WATER_CENTER: { TILE_MAP_INDEX: number }
      WATER_EDGE_TOP: { TILE_MAP_INDEX: number }
      WATER_EDGE_BOTTOM: { TILE_MAP_INDEX: number }
      WATER_EDGE_LEFT: { TILE_MAP_INDEX: number }
      WATER_EDGE_RIGHT: { TILE_MAP_INDEX: number }
      WATER_CORNER_TOP_LEFT: { TILE_MAP_INDEX: number }
      WATER_CORNER_TOP_RIGHT: { TILE_MAP_INDEX: number }
      WATER_CORNER_BOTTOM_LEFT: { TILE_MAP_INDEX: number }
      WATER_CORNER_BOTTOM_RIGHT: { TILE_MAP_INDEX: number }
    }
  }
  RESOURCE_LAYER: {
    TREE_TRUNK: { TILE_MAP_INDEX: number }
    TREE_TOP: { TILE_MAP_INDEX: number }
    LONG_GRASS_ONE: { TILE_MAP_INDEX: number }
    LONG_GRASS_TWO: { TILE_MAP_INDEX: number }
    BERRIES: { TILE_MAP_INDEX: number }
    MUSHROOM: { TILE_MAP_INDEX: number }
  }
  DECORATION_LAYER: {
    TREE_STUMP: { TILE_MAP_INDEX: number }
    FLOWERS: { TILE_MAP_INDEX: number }
  }
}

export const TILE_VARIANTS: TILE_VARIANTSI = {
  GROUND_LAYER: {
    GRASS: { TILE_MAP_INDEX: 0 },
    DIRT: { TILE_MAP_INDEX: 5 },
    MOUNTAIN: { TILE_MAP_INDEX: 23 },
    WATER: {
      WATER_CENTER: { TILE_MAP_INDEX: 133 },
      WATER_EDGE_TOP: { TILE_MAP_INDEX: 117 },
      WATER_EDGE_BOTTOM: { TILE_MAP_INDEX: 149 },
      WATER_EDGE_LEFT: { TILE_MAP_INDEX: 132 },
      WATER_EDGE_RIGHT: { TILE_MAP_INDEX: 134 },
      WATER_CORNER_TOP_LEFT: { TILE_MAP_INDEX: 116 },
      WATER_CORNER_TOP_RIGHT: { TILE_MAP_INDEX: 118 },
      WATER_CORNER_BOTTOM_LEFT: { TILE_MAP_INDEX: 148 },
      WATER_CORNER_BOTTOM_RIGHT: { TILE_MAP_INDEX: 150 }
    }
  },
  RESOURCE_LAYER: {
    TREE_TRUNK: { TILE_MAP_INDEX: 42 },
    TREE_TOP: { TILE_MAP_INDEX: 26 },
    LONG_GRASS_ONE: { TILE_MAP_INDEX: 45 },
    LONG_GRASS_TWO: { TILE_MAP_INDEX: 50 },
    BERRIES: { TILE_MAP_INDEX: 52 },
    MUSHROOM: { TILE_MAP_INDEX: 13 }
  },
  DECORATION_LAYER: {
    TREE_STUMP: { TILE_MAP_INDEX: 54 },
    FLOWERS: { TILE_MAP_INDEX: 2 }
  }
}
